INSERT INTO ricette (titolo, lista_ingredienti, foto_url, tempo_preparazione, porzioni, testo_ricetta) VALUES ('Pasta al Pomodoro', '400g di pasta, 300g di pomodori pelati, 2 spicchi di aglio, sale, olio d''oliva', 'https://www.giallozafferano.it/images/221-22163/Spaghetti-al-pomodoro_650x433_wm.jpg', 30, 4, 'Cuocere la pasta. In una padella, soffriggere l''aglio nell''olio, aggiungere i pomodori e cuocere per 20 minuti. Condire la pasta con il sugo.');
INSERT INTO ricette (titolo, lista_ingredienti, foto_url, tempo_preparazione, porzioni, testo_ricetta) VALUES ('Tiramisù', '3 uova, 100g di zucchero, 300g di mascarpone, 200g di savoiardi, caffè, cacao in polvere', 'https://upload.wikimedia.org/wikipedia/commons/5/58/Tiramisu_-_Raffaele_Diomede.jpg', 240, 6, 'Comporre il tiramisù alternando strati di savoiardi inzuppati nel caffè e crema al mascarpone. Lasciare in frigo per almeno 4 ore.');
INSERT INTO ricette (titolo, lista_ingredienti, foto_url, tempo_preparazione, porzioni, testo_ricetta) VALUES ('Risotto ai Funghi', '300g di riso, 200g di funghi, 1 cipolla, brodo, parmigiano, burro, sale, pepe', 'https://loconteilbenedellanatura.it/wp-content/uploads/2020/12/50.jpg', 45, 4, 'Preparare il risotto soffriggendo la cipolla, aggiungendo il riso e i funghi, e cuocendo con il brodo fino a cottura. Mantecare con burro e parmigiano.');
INSERT INTO ricette (titolo, lista_ingredienti, foto_url, tempo_preparazione, porzioni, testo_ricetta) VALUES ('Pizza Margherita', '300g di farina, 200ml di acqua, 10g di lievito, 1 cucchiaio di olio, 1 cucchiaino di sale, 150g di pomodoro, 100g di mozzarella, basilico', 'https://images.prismic.io/eataly-us/ed3fcec7-7994-426d-a5e4-a24be5a95afd_pizza-recipe-main.jpg?auto=compress,format', 120, 2, 'Preparare l''impasto e lasciarlo lievitare. Stendere la pizza, condire con pomodoro, mozzarella e basilico, e cuocere in forno a 250°C per 15 minuti.');
INSERT INTO ricette (titolo, lista_ingredienti, foto_url, tempo_preparazione, porzioni, testo_ricetta) VALUES ('Pancakes', '200g di farina, 300ml di latte, 2 uova, 50g di burro, 1 cucchiaino di zucchero, 1 pizzico di sale, sciroppo d''acero', 'https://cdn.cook.stbm.it/thumbnails/ricette/142/142776/hd750x421.jpg', 30, 4, 'Mescolare gli ingredienti secchi. Aggiungere le uova e il latte, e mescolare fino ad ottenere un composto omogeneo. Cuocere i pancakes in una padella e servire con sciroppo d''acero.');
INSERT INTO categorie (nome) VALUES ('Antipasto');
INSERT INTO categorie (nome) VALUES ('Primo Piatto');
INSERT INTO categorie (nome) VALUES ('Secondo Piatto');
INSERT INTO categorie (nome) VALUES ('Contorno');
INSERT INTO categorie (nome) VALUES ('Dessert');

